import './globals.css'
import '../public/custom.css'
import { Inter } from 'next/font/google'
import Navbar from './(components)/navbar/navbar'
import {Providers} from './providers'
import { SessionProvider } from 'next-auth/react';

const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
   
      <Providers> 
      <Navbar />
        {children}</Providers>
     
       </body>
    </html>
  )
}
